language: php

dist: bionic

php: 8.0

notifications:
  email:
    - team@appwrite.io

before_script:
  - sudo apt-get update
  - sudo apt-get -y install libc-ares-dev
  - pecl install --configureoptions 'enable-sockets="yes" enable-openssl="yes" enable-http2="yes" enable-mysqlnd="yes" enable-swoole-json="no" enable-swoole-curl="yes" enable-cares="yes" enable-brotli="yes"' swoole
  - composer install --ignore-platform-reqs

script:
  - docker-compose up -d
  - vendor/bin/phpunit --configuration phpunit.xml
  - vendor/bin/psalm --show-info=true
