services:
  tests:
    container_name: tests
    image_name: websockets-dev
    build:
      context: .
    volumes:
      - ./src:/usr/src/code/src
      - ./tests:/usr/src/code/tests
      - ./phpunit.xml:/usr/src/code/phpunit.xml
    networks:
        - websockets

  swoole:
    container_name: swoole
    image_name: websockets-dev
    command: php tests/servers/Swoole/server.php
    volumes:
      - ./src:/usr/src/code/src
      - ./tests:/usr/src/code/tests
      - ./phpunit.xml:/usr/src/code/phpunit.xml
    networks:
      - websockets
    ports:
      - "8001:80"

  workerman:
    container_name: workerman
    image_name: websockets-dev
    command: php tests/servers/Workerman/server.php start
    volumes:
      - ./src:/usr/src/code/src
      - ./tests:/usr/src/code/tests
      - ./phpunit.xml:/usr/src/code/phpunit.xml
    networks:
      - websockets
    ports:
      - "8002:80"

networks:
    websockets: