name: "Tests"

on: [pull_request]
jobs:
  tests:
    name: Unit & E2E
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: recursive

      - run: git checkout HEAD^2

      - name: Start Servers
        run:  docker compose up -d && sleep 10

      - name: Run Tests
        run: docker compose exec tests vendor/bin/phpunit