name: "Tests"

on: [pull_request]
jobs:
  tests:
    name: Unit & E2E
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [
          '8.0',
          '8.1',
          '8.2',
          '8.3'
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: recursive

      - run: git checkout HEAD^2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: php-${{ matrix.php-versions }}.Dockerfile
          push: false
          tags: websocket-${{ matrix.php-versions }}-dev
          load: true
          outputs: type=cacheonly
          cache-from: type=gha,scope=${{ matrix.php-versions }}
          cache-to: type=gha,mode=max,scope=${{ matrix.php-versions }}

      - name: Start Containers
        run:  |
          export PHP_VERSION=${{ matrix.php-versions }} 
          docker compose up -d
          sleep 10

      - name: Run Tests
        run: docker compose exec tests vendor/bin/phpunit
        